services:
  mysql:
    image: mysql:8.4
    container_name: mysql-lab
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: training_db
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-lab
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

